# Generated by Django 3.1.3 on 2021-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'db_table': 'color',
                'ordering': ['-id', '-nombre'],
            },
        ),
    ]
