# Generated by Django 3.1.3 on 2020-12-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(blank=True, default=None, null=True)),
                ('fecha_entrega', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'ALQUILADA'), (1, 'ENTREGADA'), (2, 'ANULADA')], default=0)),
            ],
            options={
                'verbose_name': 'alquiler',
                'verbose_name_plural': 'alquileres',
                'db_table': 'alquiler',
            },
        ),
        migrations.CreateModel(
            name='Detalle_alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvp_by_alquiler', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alquiler.alquiler')),
            ],
            options={
                'verbose_name': 'detalle_alquiler',
                'verbose_name_plural': 'detalle_alquiler',
                'db_table': 'detalle_alquiler',
            },
        ),
    ]
