# Generated by Django 3.1.3 on 2020-12-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquiler', '0001_initial'),
        ('inventario_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_alquiler',
            name='inventario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario_productos.inventario_producto'),
        ),
    ]
