# Generated by Django 3.1.3 on 2020-12-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_productos', '0003_auto_20201204_1227'),
        ('alquiler', '0002_alquiler_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_alquiler',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalle_alquiler',
            name='inventario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario_productos.inventario_producto'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.IntegerField(choices=[(0, 'ALQUILADA'), (1, 'ENTREGADA'), (2, 'ANULADA')], default=0),
        ),
    ]
