# Generated by Django 3.1.3 on 2021-01-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaccion', '0001_initial'),
        ('alquiler', '0002_detalle_alquiler_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccion.transaccion'),
        ),
    ]
