# Generated by Django 3.1.3 on 2020-12-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_alquiler_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.IntegerField(choices=[(0, 'ALQUILADA'), (1, 'ENTREGADA'), (2, 'ANULADA'), (3, 'RESERVADA')], default=0),
        ),
    ]
