# Generated by Django 3.1.3 on 2021-04-16 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_color'),
        ('alquiler', '0003_alquiler_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_alquiler',
            name='inventario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
    ]
