# Generated by Django 3.1.3 on 2020-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_pvp_alq'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pvp_confec',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
