# Generated by Django 3.1.3 on 2020-11-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_instalacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='instalacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='p_compra',
        ),
    ]
