# Generated by Django 3.1.3 on 2020-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20201122_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Producto'), (0, 'Material')], default=0),
        ),
    ]
