# Generated by Django 3.1.3 on 2020-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Producto'), (0, 'Material')], default=1),
        ),
    ]
