# Generated by Django 3.1.3 on 2021-04-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'PENDIENTE'), (1, 'ENTREGADA'), (2, 'ANULADA'), (3, 'RESERVADA')], default=0)),
            ],
            options={
                'verbose_name': 'confeccion',
                'verbose_name_plural': 'confeccion',
                'db_table': 'confeccion',
            },
        ),
        migrations.CreateModel(
            name='Detalle_confeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvp_by_confec', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('confeccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='confeccion.confeccion')),
            ],
            options={
                'verbose_name': 'detalle_confeccion',
                'verbose_name_plural': 'detalle_confecciones',
                'db_table': 'detalle_confeccion',
            },
        ),
    ]
