# Generated by Django 3.1.3 on 2020-11-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confeccion', '0001_initial'),
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confeccion',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccion.transaccion'),
        ),
    ]
