# Generated by Django 3.1.3 on 2020-12-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confeccion', '0002_confeccion_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confeccion',
            name='estado',
            field=models.IntegerField(choices=[(0, 'PENDIENTE'), (1, 'ENTREGADA'), (2, 'ANULADA'), (3, 'RESERVADA')], default=0),
        ),
    ]
