# Generated by Django 3.1.3 on 2021-04-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0009_remove_asig_recurso_lote'),
        ('confeccion', '0003_confeccion_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='confeccion',
            name='confeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asignar_recursos.asig_recurso'),
        ),
    ]
