# Generated by Django 3.1.3 on 2021-04-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0009_remove_asig_recurso_lote'),
        ('confeccion', '0004_confeccion_confeccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_confeccion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalle_confeccion',
            name='confeccion',
        ),
        migrations.AlterField(
            model_name='detalle_confeccion',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='asignar_recursos.detalle_produccion'),
        ),
    ]
