# Generated by Django 3.1.3 on 2021-04-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0009_remove_asig_recurso_lote'),
        ('confeccion', '0005_auto_20210427_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_confeccion',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignar_recursos.detalle_produccion'),
        ),
    ]
