# Generated by Django 3.1.3 on 2021-05-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confeccion', '0006_auto_20210427_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_confeccion',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalle_confeccion',
            name='confeccion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='confeccion.confeccion'),
        ),
    ]
