# Generated by Django 3.1.3 on 2021-05-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0009_remove_asig_recurso_lote'),
        ('confeccion', '0007_auto_20210502_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_confeccion',
            name='confeccion',
        ),
        migrations.AddField(
            model_name='detalle_confeccion',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='asignar_recursos.detalle_produccion'),
        ),
    ]
