# Generated by Django 3.1.3 on 2020-12-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'En stock'), (0, 'Utilizado')], default=1)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.material')),
            ],
            options={
                'verbose_name': 'inventario_material',
                'verbose_name_plural': 'inventario_materiales',
                'db_table': 'inventario_material',
                'ordering': ['-id'],
            },
        ),
    ]
