# Generated by Django 3.1.3 on 2020-12-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('inventario_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.material'),
        ),
    ]
