# Generated by Django 3.1.3 on 2020-12-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_material',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En stock'), (0, 'Utilizado')], default=1),
        ),
    ]
