# Generated by Django 3.1.3 on 2020-11-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedor_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['-nombre', '-num_doc', '-direccion'], 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='numero_documento',
            new_name='num_doc',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='documento',
            new_name='tipo',
        ),
    ]
