# Generated by Django 3.1.3 on 2021-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad', models.IntegerField(choices=[(3, 'EXELENTE'), (2, 'BUENO'), (1, 'REGULAR'), (0, 'MALO')], default=2)),
                ('p_compra', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('unidad_medida', models.IntegerField(choices=[(1, 'Metros'), (0, 'Unidad')], default=0)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'db_table': 'material',
                'ordering': ['-id'],
            },
        ),
    ]
