# Generated by Django 3.1.3 on 2021-01-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_material', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='calidad',
            field=models.IntegerField(choices=[(3, 'EXELENTE'), (2, 'BUENO'), (1, 'REGULAR'), (0, 'MALO')], default=2),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='medida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tipo_material.tipo_material'),
        ),
        migrations.AddField(
            model_name='material',
            name='ud_medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
