# Generated by Django 3.1.3 on 2021-04-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20210410_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_actual',
            field=models.IntegerField(default=1),
        ),
    ]
