# Generated by Django 3.1.1 on 2020-11-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_p_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='instalacion',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0),
        ),
    ]
