# Generated by Django 3.1.3 on 2021-04-11 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
        ('material', '0003_material_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='color.color'),
        ),
    ]
