# Generated by Django 3.1.3 on 2021-04-10 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'DISPONIBLE'), (1, 'EN USO'), (2, 'EN MANTENIMIENTO')], default=0)),
                ('serie', models.CharField(default=0, max_length=50)),
            ],
            options={
                'verbose_name': 'maquina',
                'verbose_name_plural': 'maquinas',
                'db_table': 'maquina',
                'ordering': ['-id', '-tipo'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_maquina',
                'verbose_name_plural': 'Tipo_maquinas',
                'db_table': 'Tipo_maquina',
                'ordering': ['-id', '-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Maquina_mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquina.maquina')),
            ],
            options={
                'verbose_name': 'maquina_mantenimiento',
                'verbose_name_plural': 'maquina_mantenimientos',
                'db_table': 'maquina_mantenimiento',
                'ordering': ['-id', '-fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquina.tipo_maquina'),
        ),
    ]
