# Generated by Django 3.1.3 on 2020-12-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquina', '0002_maquina_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='serie',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
