# Generated by Django 3.1.3 on 2020-11-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='fecha',
            new_name='fecha_pago',
        ),
    ]
