# Generated by Django 3.1.3 on 2021-04-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('gasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa'),
        ),
    ]
