# Generated by Django 3.1.3 on 2021-04-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('gasto', '0002_auto_20210410_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa'),
        ),
    ]
