# Generated by Django 3.1.3 on 2021-04-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'USUARIO'), (0, 'CLIENTE')], default=1),
        ),
    ]
