# Generated by Django 3.1.3 on 2020-12-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201216_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'USER'), (0, 'CLIENTE')], default=1),
        ),
    ]
