# Generated by Django 3.1.3 on 2020-12-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        ('producto', '0001_initial'),
        ('inventario_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_producto',
            name='produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.produccion'),
        ),
        migrations.AlterField(
            model_name='inventario_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
    ]
