# Generated by Django 3.1.3 on 2020-12-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario_producto',
            options={'ordering': ['id'], 'verbose_name': 'inventario_producto', 'verbose_name_plural': 'inventario_productos'},
        ),
    ]
