# Generated by Django 3.1.3 on 2020-12-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_productos', '0002_auto_20201203_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_producto',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En stock'), (0, 'Vendido'), (2, 'Alquilado')], default=1),
        ),
    ]
