# Generated by Django 3.1.3 on 2020-12-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvp_rep_by_prod', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'detalle_reparcion',
                'verbose_name_plural': 'detalles_reparciones',
                'db_table': 'detalle_reparcion',
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, default=None, null=True)),
                ('fecha_entrega', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'POR ENTREGAR'), (1, 'ENTREGADA'), (2, 'ANULADA')], default=0)),
            ],
            options={
                'verbose_name': 'reparacion',
                'verbose_name_plural': 'reparaciones',
                'db_table': 'reparacion',
            },
        ),
    ]
