# Generated by Django 3.1.3 on 2020-12-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion', '0002_auto_20201207_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.IntegerField(choices=[(0, 'POR ENTREGAR'), (1, 'ENTREGADA'), (2, 'ANULADA'), (3, 'RESERVADA')], default=0),
        ),
    ]
