# Generated by Django 3.1.3 on 2020-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion', '0002_auto_20201130_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='fecha_entrega',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
