# Generated by Django 3.1.3 on 2021-04-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0008_auto_20210413_2003'),
        ('reparacion', '0002_auto_20210410_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_reparacion',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='detalle_reparacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asignar_recursos.detalle_produccion'),
        ),
    ]
