# Generated by Django 3.1.3 on 2020-12-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion', '0003_auto_20201203_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.IntegerField(choices=[(0, 'PENDIENTE'), (1, 'ENTREGADA')], default=0),
        ),
    ]
