# Generated by Django 3.1.3 on 2021-04-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_color'),
        ('reparacion', '0004_auto_20210426_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_reparacion',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle_reparacion',
            name='producto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.IntegerField(choices=[(0, 'POR ENTREGAR'), (1, 'ENTREGADA'), (2, 'ANULADA'), (3, 'RESERVADA')], default=0),
        ),
    ]
