# Generated by Django 3.1.3 on 2020-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion', '0004_auto_20201203_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.IntegerField(choices=[(0, 'POR ENTREGAR'), (1, 'ENTREGADA'), (2, 'ANULADA')], default=0),
        ),
    ]
