# Generated by Django 3.1.3 on 2020-12-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitioWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('mision', models.CharField(max_length=500)),
                ('vision', models.CharField(max_length=500)),
                ('mapa', models.CharField(max_length=10000)),
            ],
            options={
                'verbose_name': 'sitio',
                'db_table': 'sitio',
                'ordering': ['id', 'titulo'],
            },
        ),
    ]
