# Generated by Django 3.1.3 on 2021-05-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitioweb',
            name='mapa',
        ),
    ]
