# Generated by Django 3.1.1 on 2020-11-07 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
