# Generated by Django 3.1.3 on 2021-01-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignar_recursos', '0001_initial'),
        ('inventario_material', '0001_initial'),
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_asig_recurso',
            name='inventario_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_material.inventario_material'),
        ),
        migrations.AddField(
            model_name='detalle_asig_maquina',
            name='asig_recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignar_recursos.asig_recurso'),
        ),
        migrations.AddField(
            model_name='detalle_asig_maquina',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquina.maquina'),
        ),
    ]
