# Generated by Django 3.1.3 on 2020-12-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maquina', '0001_initial'),
        ('asignar_recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_asig_recurso',
            name='maquina',
        ),
        migrations.AddField(
            model_name='asig_recurso',
            name='lote',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Detalle_asig_maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asig_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignar_recursos.asig_recurso')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquina.maquina')),
            ],
            options={
                'verbose_name': 'detalle_asig_maquina',
                'verbose_name_plural': 'detalle_asig_maquinas',
                'db_table': 'detalle_asig_maquina',
            },
        ),
    ]
