# Generated by Django 3.1.3 on 2021-04-10 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0002_auto_20210410_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asig_recurso',
            name='inventariado',
        ),
        migrations.AddField(
            model_name='asig_recurso',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='novedad',
            field=models.CharField(default='Sin novedad', max_length=1000),
        ),
    ]
