# Generated by Django 3.1.3 on 2021-04-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_stock_actual'),
        ('asignar_recursos', '0003_auto_20210410_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_asig_recurso',
            name='inventario_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material'),
        ),
    ]
