# Generated by Django 3.1.3 on 2020-12-04 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignar_recursos', '0003_auto_20201204_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='asig_recurso',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
