# Generated by Django 3.1.3 on 2020-12-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0004_asig_recurso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asig_recurso',
            name='estado',
            field=models.IntegerField(choices=[(0, 'ANULADA'), (1, 'FINALIZADA')], default=1),
        ),
    ]
