# Generated by Django 3.1.3 on 2020-12-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0004_auto_20201206_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_asig_recurso',
            name='cantidad',
        ),
    ]
