# Generated by Django 3.1.3 on 2021-04-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0004_auto_20210410_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_asig_recurso',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
