# Generated by Django 3.1.3 on 2020-12-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0005_remove_detalle_asig_recurso_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='asig_recurso',
            name='inventariado',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0),
        ),
    ]
