# Generated by Django 3.1.3 on 2020-12-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_material', '0002_inventario_material_estado'),
        ('asignar_recursos', '0005_asig_recurso_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_asig_recurso',
            name='material',
        ),
        migrations.AddField(
            model_name='detalle_asig_recurso',
            name='inventario_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_material.inventario_material'),
        ),
    ]
