# Generated by Django 3.1.3 on 2021-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0005_detalle_asig_recurso_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_asig_recurso',
            name='ingreso_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalle_asig_recurso',
            name='ingreso_inicial',
            field=models.IntegerField(default=1),
        ),
    ]
