# Generated by Django 3.1.3 on 2020-12-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0006_auto_20201204_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_asig_recurso',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asig_recurso',
            name='estado',
            field=models.IntegerField(choices=[(0, 'ANULADA'), (1, 'EN PRODUCCION'), (2, 'FINALIZADA')], default=1),
        ),
    ]
