# Generated by Django 3.1.3 on 2021-04-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0006_auto_20210412_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_perdidas_materiales',
            options={'ordering': ['id'], 'verbose_name': 'detalle_perdidas_material', 'verbose_name_plural': 'detalle_perdidas_materiales'},
        ),
        migrations.RemoveField(
            model_name='detalle_perdidas_materiales',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='detalle_perdidas_materiales',
            name='material',
        ),
        migrations.AddField(
            model_name='detalle_perdidas_materiales',
            name='det_asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asignar_recursos.detalle_asig_recurso'),
        ),
    ]
