# Generated by Django 3.1.3 on 2020-12-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0006_asig_recurso_inventariado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asig_recurso',
            name='lote',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
