# Generated by Django 3.1.3 on 2021-04-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0008_auto_20210413_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asig_recurso',
            name='lote',
        ),
    ]
