# Generated by Django 3.1.3 on 2020-12-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0009_auto_20201206_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asig_recurso',
            name='lote',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
