# Generated by Django 3.1.3 on 2020-12-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_recursos', '0011_auto_20201206_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asig_recurso',
            name='lote',
        ),
    ]
