# Generated by Django 3.1.3 on 2020-11-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0002_det_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_salida',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Venta'), (1, 'Reparacion'), (2, 'Alquiler'), (3, 'Confeccion')], default=0),
        ),
        migrations.AlterField(
            model_name='detalle_alquiler',
            name='estado_ingreso',
            field=models.IntegerField(choices=[(0, 'Bueno'), (1, 'Regular'), (2, 'Malo')]),
        ),
        migrations.AlterField(
            model_name='detalle_alquiler',
            name='estado_salida',
            field=models.IntegerField(choices=[(0, 'Bueno'), (1, 'Regular'), (2, 'Malo')]),
        ),
    ]
