# Generated by Django 3.1.3 on 2021-04-11 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20210410_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compra',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='stock_inicial',
        ),
    ]
