# Generated by Django 3.1.3 on 2021-02-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='comprobante',
            field=models.IntegerField(default=1),
        ),
    ]
