# Generated by Django 3.1.3 on 2021-02-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_compra_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comprobante',
            field=models.IntegerField(unique=True),
        ),
    ]
