# Generated by Django 3.1.3 on 2020-11-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0007_producto_pcp'),
        ('transaccion', '0004_auto_20201127_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'DEVUELTA'), (1, 'FINALIZADA')], default=1)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccion.transaccion')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvp_actual', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('producto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaccion.transaccion')),
            ],
            options={
                'verbose_name': 'detalle_venta',
                'verbose_name_plural': 'detalles_ventas',
                'db_table': 'detalle_venta',
            },
        ),
    ]
