# Generated by Django 3.1.3 on 2020-12-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_productos', '0002_auto_20201206_1101'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario_productos.inventario_producto'),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='pvp_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
