# Generated by Django 3.1.3 on 2021-04-14 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_color'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
    ]
