# Generated by Django 3.1.3 on 2020-12-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(0, 'DEVUELTA'), (1, 'FINALIZADA'), (2, 'RESERVADA')], default=1),
        ),
    ]
