# Generated by Django 3.1.3 on 2021-01-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.IntegerField()),
                ('eqv_letra', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'talla',
                'verbose_name_plural': 'tallas',
                'db_table': 'talla',
                'ordering': ['-id', '-talla'],
            },
        ),
    ]
