# Generated by Django 3.1.3 on 2021-04-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talla', '0002_auto_20210410_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talla',
            name='eqv_letra',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
