# Generated by Django 3.1.3 on 2021-01-22 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to='')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'databasebackups',
                'db_table': 'databasebackups',
                'ordering': ['-id'],
            },
        ),
    ]
