# Generated by Django 3.1.1 on 2020-11-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseBackups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasebackups',
            name='fecha',
        ),
    ]
