# Generated by Django 3.1.1 on 2020-11-09 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseBackups', '0002_remove_databasebackups_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackups',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
