# Generated by Django 3.1.3 on 2020-11-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseBackups', '0003_databasebackups_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseBackups',
        ),
    ]
