# Generated by Django 3.1.3 on 2020-12-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0001_initial'),
        ('producto_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_base',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presentacion.presentacion'),
        ),
    ]
