# Generated by Django 3.1.3 on 2021-02-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_base', '0002_remove_producto_base_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_base',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'MATERIAL'), (0, 'PRODUCTO')], default=0),
        ),
    ]
