# Generated by Django 3.1.3 on 2021-04-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_base', '0003_auto_20210410_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_base',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'PRODUCTO'), (1, 'MATERIAL')], default=0),
        ),
    ]
