# Generated by Django 3.1.3 on 2021-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_base', '0016_auto_20210427_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_base',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'MATERIAL'), (0, 'PRODUCTO')], default=0),
        ),
    ]
