# Generated by Django 3.1.3 on 2021-05-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_base', '0017_auto_20210427_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_base',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'PRODUCTO'), (1, 'MATERIAL')], default=0),
        ),
    ]
