# Generated by Django 3.1.3 on 2020-11-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='venta',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Detalle_compra',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
