# Generated by Django 3.1.1 on 2020-11-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='iva',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
    ]
