# Generated by Django 3.1.3 on 2021-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'tipo_material',
                'verbose_name_plural': 'tipo_materiales',
                'db_table': 'tipo_material',
                'ordering': ['-id', '-nombre'],
            },
        ),
    ]
